functionsDirectory = "C:\\Users\\EstevesZe\\the-brief\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\EstevesZe\\the-brief\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\EstevesZe\\the-brief\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]